In [1]:
import pandas as pd

In [3]:
data_1 = pd.read_csv('data/201901-202003.csv')
data_1.head()

,REG_YYMM,CARD_SIDO_NM,CARD_CCG_NM,STD_CLSS_NM,HOM_SIDO_NM,HOM_CCG_NM,AGE,SEX_CTGO_CD,FLC,CSTMR_CNT,AMT,CNT
0,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,20s,1,1,4,311200,4
1,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,30s,1,2,7,1374500,8
2,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,30s,2,2,6,818700,6
3,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,40s,1,3,4,1717000,5
4,201901,강원,강릉시,건강보조식품 소매업,강원,강릉시,40s,1,4,3,1047300,3

In [4]:
data_2 = pd.read_csv('data/submission.csv')
data_2.head()

   id  REG_YYMM CARD_SIDO_NM           STD_CLSS_NM  AMT
0   0    202004           강원            건강보조식품 소매업    0
1   1    202004           강원               골프장 운영업    0
2   2    202004           강원           과실 및 채소 소매업    0
3   3    202004           강원     관광 민예품 및 선물용품 소매업    0
4   4    202004           강원  그외 기타 분류안된 오락관련 서비스업    0